// <auto-generated />
using System;
using EFDDD.Infrastructure.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFDDD.Infrastructure.Migrations
{
    [DbContext(typeof(AndersonDBContext))]
    [Migration("20251229110642_V0001")]
    partial class V0001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFDDD.Domain.Entities.LogEntity", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("EFDDD.Domain.Entities.ProductEntity", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("EFDDD.Domain.Entities.ProductItemEntity", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductItemNo")
                        .HasColumnType("int");

                    b.Property<string>("ProductItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId", "ProductItemNo");

                    b.ToTable("ProductItem", (string)null);
                });

            modelBuilder.Entity("EFDDD.Domain.Entities.ProductItemEntity", b =>
                {
                    b.HasOne("EFDDD.Domain.Entities.ProductEntity", "Product")
                        .WithMany("ProductItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EFDDD.Domain.ValueObjects.GlobalPrice", "GlobalPrice", b1 =>
                        {
                            b1.Property<int>("ProductItemEntityProductId")
                                .HasColumnType("int");

                            b1.Property<int>("ProductItemEntityProductItemNo")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.HasKey("ProductItemEntityProductId", "ProductItemEntityProductItemNo");

                            b1.ToTable("ProductItem");

                            b1.WithOwner()
                                .HasForeignKey("ProductItemEntityProductId", "ProductItemEntityProductItemNo");
                        });

                    b.Navigation("GlobalPrice")
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EFDDD.Domain.Entities.ProductEntity", b =>
                {
                    b.Navigation("ProductItems");
                });
#pragma warning restore 612, 618
        }
    }
}
